name: Java CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "34 6 * * *"

jobs:
  build:
    strategy:
      matrix:
        java_version: ['17', '21']
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: "temurin"

      - name: Build with Maven
        run: mvn -ntp --batch-mode --update-snapshots package

      - name: Maven install
        run: mvn -ntp --batch-mode clean install